// 1. データ定義
const characterData = [
    { id: "c01", name: "ソニック", type: "スピード", speed: 20, accel: 5, handling: 13, power: 15, dash: 7 },
    { id: "c02", name: "テイルス", type: "アクセル", speed: 15, accel: 20, handling: 7, power: 13, dash: 5 },
    { id: "c03", name: "ナックルズ", type: "パワー", speed: 13, accel: 8, handling: 5, power: 18, dash: 16 },
    { id: "c04", name: "エミー", type: "ハンドリング", speed: 5, accel: 15, handling: 20, power: 7, dash: 13 },
    { id: "c05", name: "クリーム＆チーズ", type: "ハンドリング", speed: 7, accel: 14, handling: 19, power: 9, dash: 11 },
    { id: "c06", name: "ビッグ", type: "パワー", speed: 12, accel: 10, handling: 7, power: 17, dash: 14 },
    { id: "c07", name: "シルバー", type: "ハンドリング", speed: 7, accel: 13, handling: 20, power: 9, dash: 11 },
    { id: "c08", name: "ブレイズ", type: "スピード", speed: 20, accel: 7, handling: 11, power: 13, dash: 9 },
    { id: "c09", name: "シャドウ", type: "スピード", speed: 20, accel: 7, handling: 11, power: 13, dash: 9 },
    { id: "c10", name: "ルージュ", type: "ハンドリング", speed: 5, accel: 16, handling: 19, power: 7, dash: 13 },
    { id: "c11", name: "オメガ", type: "パワー", speed: 11, accel: 9, handling: 7, power: 20, dash: 13 },
    { id: "c12", name: "ベクター", type: "パワー", speed: 13, accel: 7, handling: 5, power: 19, dash: 16 },
    { id: "c13", name: "エスピオ", type: "スピード", speed: 17, accel: 5, handling: 14, power: 16, dash: 8 },
    { id: "c14", name: "チャーミー", type: "アクセル", speed: 14, accel: 18, handling: 10, power: 11, dash: 7 },
    { id: "c15", name: "ザボック", type: "パワー", speed: 13, accel: 7, handling: 5, power: 20, dash: 15 },
    { id: "c16", name: "ザズ", type: "アクセル", speed: 16, accel: 18, handling: 8, power: 13, dash: 5 },
    { id: "c17", name: "エッグマン", type: "パワー", speed: 14, accel: 8, handling: 5, power: 17, dash: 16 },
    { id: "c18", name: "メタルソニック", type: "スピード", speed: 19, accel: 5, handling: 13, power: 16, dash: 7 },
    { id: "c19", name: "エッグポーン", type: "アクセル", speed: 16, accel: 17, handling: 8, power: 14, dash: 5 },
    { id: "c20", name: "セージ", type: "アクセル", speed: 14, accel: 17, handling: 10, power: 12, dash: 7 },
    { id: "c21", name: "ジェット", type: "スピード", speed: 19, accel: 7, handling: 11, power: 14, dash: 9 },
    { id: "c22", name: "ウェーブ", type: "アクセル", speed: 16, accel: 19, handling: 7, power: 13, dash: 5 },
    { id: "c23", name: "ストーム", type: "パワー", speed: 11, accel: 9, handling: 7, power: 19, dash: 14 },
    { id: "c24", name: "スーパーソニック", type: "スピード", speed: 20, accel: 20, handling: 20, power: 20, dash: 20 },
    { id: "c28", name: "ウェアホッグ", type: "パワー", speed: 14, accel: 9, handling: 6, power: 16, dash: 15 },
    { id: "c30", name: "ナイン", type: "アクセル", speed: 15, accel: 20, handling: 7, power: 13, dash: 5 },
    { id: "c32", name: "ドレッド", type: "パワー", speed: 13, accel: 7, handling: 5, power: 20, dash: 15 },
    { id: "c34", name: "ラスティ", type: "ハンドリング", speed: 5, accel: 15, handling: 20, power: 7, dash: 13 },
    { id: "c38", name: "ジョーカー", type: "ハンドリング", speed: 7, accel: 14, handling: 18, power: 10, dash: 11 },
    { id: "c40", name: "春日一番", type: "パワー", speed: 12, accel: 11, handling: 8, power: 16, dash: 13 },
    { id: "c36", name: "初音ミク", type: "ダッシュ", speed: 9, accel: 14, handling: 15, power: 6, dash: 16 },
    { id: "c41", name: "スティーブ", type: "パワー", speed: 12, accel: 9, handling: 6, power: 18, dash: 15 },
    { id: "c43", name: "アレックス", type: "パワー", speed: 11, accel: 10, handling: 7, power: 18, dash: 14 },
    { id: "c45", name: "クリーパー", type: "アクセル", speed: 14, accel: 19, handling: 9, power: 11, dash: 7 },
    { id: "c47", name: "スポンジ・ボブ", type: "ハンドリング", speed: 7, accel: 14, handling: 16, power: 10, dash: 13 },
    { id: "c49", name: "パトリック", type: "パワー", speed: 13, accel: 9, handling: 6, power: 17, dash: 15 }
];

const machineParts = [
    // 1. スピードタイプ
    { id: "ms01", type: "スピード", name: "スピードスターライトニング", s: 20, a: 5, h: 13, p: 15, d: 7 },
    { id: "ms02", type: "スピード", name: "ダークリーパー", s: 20, a: 6, h: 12, p: 14, d: 8 },
    { id: "ms03", type: "スピード", name: "ミラージュブレイド", s: 19, a: 7, h: 11, p: 14, d: 9 },
    { id: "ms04", type: "スピード", name: "スーパーシャイニング", s: 18, a: 5, h: 13, p: 16, d: 8 },
    { id: "ms05", type: "スピード", name: "ロイヤルチャリオット", s: 20, a: 7, h: 11, p: 13, d: 9 },
    { id: "ms06", type: "スピード", name: "スティルスチェイサー", s: 19, a: 6, h: 12, p: 15, d: 8 },
    { id: "ms07", type: "スピード", name: "レトロフューチャー", s: 18, a: 7, h: 11, p: 14, d: 10 },
    { id: "ms08", type: "スピード", name: "ワイルドGT", s: 19, a: 5, h: 13, p: 16, d: 7 },
    { id: "ms09", type: "スピード", name: "バスターM", s: 19, a: 5, h: 13, p: 16, d: 7 },
    { id: "ms10", type: "スピード", name: "アルセーヌウィング", s: 17, a: 6, h: 13, p: 15, d: 9 },
    // 2. アクセルタイプ
    { id: "ma01", type: "アクセル", name: "ホワールウィンド", s: 15, a: 20, h: 7, p: 13, d: 5 },
    { id: "ma02", type: "アクセル", name: "ジャンブルレイジ", s: 14, a: 20, h: 8, p: 12, d: 6 },
    { id: "ma03", type: "アクセル", name: "ハイパースコーピオン", s: 14, a: 19, h: 9, p: 11, d: 7 },
    { id: "ma04", type: "アクセル", name: "サイバースピアー", s: 15, a: 18, h: 9, p: 12, d: 6 },
    { id: "ma05", type: "アクセル", name: "ポーンキャリバー", s: 13, a: 20, h: 9, p: 11, d: 7 },
    { id: "ma06", type: "アクセル", name: "ロングノーズビー", s: 16, a: 19, h: 7, p: 13, d: 5 },
    { id: "ma07", type: "アクセル", name: "ラジカルフォース", s: 16, a: 18, h: 8, p: 13, d: 5 },
    { id: "ma08", type: "アクセル", name: "レーシングバギー", s: 14, a: 18, h: 10, p: 11, d: 7 },
    { id: "ma09", type: "アクセル", name: "ギガントライナー", s: 15, a: 19, h: 8, p: 12, d: 6 },
    // 3. ハンドリングタイプ
    { id: "mh01", type: "ハンドリング", name: "ピンクカブリオレ", s: 5, a: 15, h: 20, p: 7, d: 13 },
    { id: "mh02", type: "ハンドリング", name: "リップスパイダー", s: 6, a: 14, h: 20, p: 8, d: 12 },
    { id: "mh03", type: "ハンドリング", name: "ヴィクトリアキャリッジ", s: 7, a: 14, h: 19, p: 9, d: 11 },
    { id: "mh04", type: "ハンドリング", name: "モトビートル", s: 7, a: 14, h: 18, p: 10, d: 11 },
    { id: "mh05", type: "ハンドリング", name: "エンシェントスローン", s: 5, a: 16, h: 17, p: 8, d: 14 },
    { id: "mh06", type: "ハンドリング", name: "リトルレディー", s: 5, a: 16, h: 19, p: 7, d: 13 },
    { id: "mh07", type: "ハンドリング", name: "ホットハッチ", s: 6, a: 15, h: 19, p: 8, d: 12 },
    { id: "mh08", type: "ハンドリング", name: "フォシルロック", s: 5, a: 16, h: 18, p: 8, d: 13 },
    { id: "mh09", type: "ハンドリング", name: "ネオサイクロン", s: 7, a: 13, h: 20, p: 9, d: 11 },
    { id: "mh10", type: "ハンドリング", name: "マインカート", s: 7, a: 14, h: 16, p: 10, d: 13 },
    { id: "mh11", type: "ハンドリング", name: "パティワゴン", s: 7, a: 14, h: 17, p: 10, d: 12 },
    // 4. パワータイプ
    { id: "mp01", type: "パワー", name: "ランドスマッシャー", s: 13, a: 7, h: 5, p: 20, d: 15 },
    { id: "mp02", type: "パワー", name: "ロードドラグーン", s: 12, a: 8, h: 6, p: 20, d: 14 },
    { id: "mp03", type: "パワー", name: "ナイトタンク", s: 12, a: 9, h: 6, p: 18, d: 15 },
    { id: "mp04", type: "パワー", name: "ファングローダー", s: 11, a: 10, h: 7, p: 18, d: 14 },
    { id: "mp05", type: "パワー", name: "ビートゲーター", s: 11, a: 9, h: 7, p: 20, d: 13 },
    { id: "mp06", type: "パワー", name: "フロッグクルーザー", s: 13, a: 7, h: 5, p: 19, d: 16 },
    { id: "mp07", type: "パワー", name: "クロスドーザー", s: 12, a: 8, h: 6, p: 19, d: 15 },
    { id: "mp08", type: "パワー", name: "トレイルランナー", s: 14, a: 8, h: 5, p: 17, d: 16 },
    { id: "mp09", type: "パワー", name: "エッグドリルスターMK2", s: 11, a: 9, h: 7, p: 19, d: 14 },
    { id: "mp10", type: "パワー", name: "ビーストスパイク", s: 12, a: 11, h: 8, p: 16, d: 13 },
    { id: "mp11", type: "パワー", name: "ドラゴンブレイブ", s: 13, a: 9, h: 6, p: 17, d: 15 },
    // 5. ダッシュタイプ
    { id: "md01", type: "ダッシュ", name: "タイプ-J イオタ", s: 13, a: 16, h: 21, p: 10, d: 30 },
    { id: "md02", type: "ダッシュ", name: "タイプ-S ストリーム", s: 12, a: 17, h: 22, p: 9, d: 30 },
    { id: "md03", type: "ダッシュ", name: "サクラボード", s: 12, a: 18, h: 22, p: 9, d: 29 },
    { id: "md04", type: "ダッシュ", name: "トリプルファン", s: 14, a: 17, h: 21, p: 10, d: 28 },
    { id: "md05", type: "ダッシュ", name: "ポップロード", s: 13, a: 18, h: 22, p: 9, d: 28 },
    { id: "md06", type: "ダッシュ", name: "タイプ-W ウィンディ", s: 11, a: 18, h: 23, p: 8, d: 30 },
    { id: "md07", type: "ダッシュ", name: "ウィスポンブースター", s: 13, a: 17, h: 21, p: 10, d: 29 },
    { id: "md08", type: "ダッシュ", name: "クワッドコプター", s: 11, a: 19, h: 23, p: 8, d: 29 },
    { id: "md09", type: "ダッシュ", name: "ジョーズロケット", s: 12, a: 19, h: 23, p: 8, d: 28 },
    { id: "md10", type: "ダッシュ", name: "ブルースター", s: 14, a: 17, h: 22, p: 10, d: 27 },
    { id: "md11", type: "ダッシュ", name: "ディーヴァマッキナ", s: 14, a: 18, h: 22, p: 10, d: 26 }
];

// ガジェットデータ
const defaultGadgets = [
    { id: "0101", name: "スタート成功ボーナス", cost: 1, type: "ring-get", desc: "スタートダッシュ成功時にリングを30枚入手" },
    { id: "0102", name: "エアトリックボーナス", cost: 1, type: "ring-get", desc: "エアトリック1回につきリングを2枚入手" },
    { id: "0103", name: "アイテム攻撃リングボーナス", cost: 1, type: "ring-get", desc: "アイテム攻撃ヒット時にリング10枚獲得" },
    { id: "0104", name: "ランオフボーナス", cost: 1, type: "ring-get", desc: "減速エリア走行中にリングを獲得し続ける" },
    { id: "0105", name: "スリップストリームボーナス", cost: 1, type: "ring-get", desc: "スリップストリーム中にリングを獲得し続ける" },
    { id: "0106", name: "トラベルリングボーナス", cost: 1, type: "ring-get", desc: "トラベルリング通過時にリング15枚獲得" },
    { id: "0107", name: "変形時アクションボーナス", cost: 1, type: "ring-get", desc: "水上・空中チャージアクションでリング4枚獲得" },
    { id: "0108", name: "ジャストチャージボーナス", cost: 2, type: "ring-get", desc: "ジャストチャージダッシュでリング獲得" },
    { id: "0109", name: "ダッシュパネルボーナス", cost: 2, type: "ring-get", desc: "ダッシュパネルでリング5枚獲得" },
    { id: "0110", name: "ダッシュパネルボーナスミニ", cost: 1, type: "ring-get", desc: "ダッシュパネルでリング2枚獲得" },
    { id: "0111", name: "ダッシュパネルボーナスコンボ", cost: 2, type: "ring-get", desc: "ダッシュパネル連続通過で獲得量アップ" },

    { id: "0201", name: "リング上限130", cost: 1, type: "ring-ability", desc: "所持上限130枚" },
    { id: "0202", name: "リング上限200", cost: 2, type: "ring-ability", desc: "所持上限200枚" },
    { id: "0203", name: "リングスティールミニ", cost: 1, type: "ring-ability", desc: "接触時リング2枚奪取" },
    { id: "0204", name: "リングスティール", cost: 2, type: "ring-ability", desc: "接触時リング5枚奪取" },
    { id: "0205", name: "リングゲットダッシュミニ", cost: 1, type: "ring-ability", desc: "リング獲得時少し加速" },
    { id: "0206", name: "リングゲットダッシュ", cost: 2, type: "ring-ability", desc: "リング獲得時大きく加速" },
    { id: "0207", name: "リング獲得範囲アップ", cost: 1, type: "ring-ability", desc: "リング吸い寄せ範囲拡大" },

    { id: "0301", name: "ロングスリップストリーム", cost: 1, type: "tech-boost", desc: "スリップストリーム距離延長" },
    { id: "0302", name: "空中ドリフト自由度アップ", cost: 1, type: "tech-boost", desc: "空中での旋回性能アップ" },
    { id: "0303", name: "チャージジャンプ自由度アップ", cost: 1, type: "tech-boost", desc: "水上チャージジャンプ時の移動制御アップ" },
    { id: "0304", name: "高速エアトリック", cost: 1, type: "tech-boost", desc: "エアトリック所要時間短縮" },
    { id: "0305", name: "超高速エアトリック", cost: 2, type: "tech-boost", desc: "エアトリック所要時間大幅短縮" },
    { id: "0306", name: "ぶつかりダッシュ", cost: 2, type: "tech-boost", desc: "接触時にダッシュ" },
    { id: "0307", name: "スピンドリフト", cost: 2, type: "tech-boost", desc: "ドリフト中回転して攻撃判定を持つ" },

    { id: "0401", name: "ファーストファストチャージ", cost: 2, type: "charge-boost", desc: "チャージ1段階目高速化" },
    { id: "0402", name: "セカンドファストチャージ", cost: 1, type: "charge-boost", desc: "チャージ2段階目高速化" },
    { id: "0403", name: "サードファストチャージ", cost: 1, type: "charge-boost", desc: "チャージ3段階目高速化" },
    { id: "0404", name: "アルティメットチャージ", cost: 2, type: "charge-boost", desc: "チャージ4段階目解禁" },
    { id: "0405", name: "ジャストチャージダッシュ", cost: 2, type: "charge-boost", desc: "ジャストタイミングでダッシュ性能アップ" },
    { id: "0406", name: "テクニカルドリフト", cost: 2, type: "charge-boost", desc: "滑りやすくなるがチャージ全段階高速化" },
    { id: "0407", name: "フリクションドリフト", cost: 2, type: "charge-boost", desc: "減速するがチャージ全段階高速化" },
    { id: "0408", name: "切りかえしクイックチャージ", cost: 3, type: "charge-boost", desc: "切り返し時にチャージ大幅増加" },

    { id: "0501", name: "スターター", cost: 1, type: "param-boost", desc: "LAP1のみ全ステータス+10" },
    { id: "0502", name: "スーパースターター", cost: 2, type: "param-boost", desc: "LAP1のみ全ステータス+20" },
    { id: "0503", name: "スロースターター", cost: 2, type: "param-boost", desc: "LAP3のみ全ステータス+10" },
    { id: "0504", name: "スーパースロースターター", cost: 3, type: "param-boost", desc: "LAP3のみ全ステータス+20" },
    { id: "0505", name: "スピードチューン1", cost: 1, type: "param-boost", desc: "スピードマシンならS+10/A-4、それ以外はS+4", calc: (s, ctx) => { if(ctx.mT==="スピード"){ s.s+=10; s.a-=4; } else { s.s+=4; } } },
    { id: "0506", name: "スピードチューン2", cost: 1, type: "param-boost", desc: "スピードマシンならS+10/A-2/D-2、それ以外はS+4", calc: (s, ctx) => { if(ctx.mT==="スピード"){ s.s+=10; s.a-=2; s.d-=2; } else { s.s+=4; } } },
    { id: "0507", name: "アクセルチューン1", cost: 1, type: "param-boost", desc: "アクセルマシンならA+10/H-4、それ以外はA+4", calc: (s, ctx) => { if(ctx.mT==="アクセル"){ s.a+=10; s.h-=4; } else { s.a+=4; } } },
    { id: "0508", name: "アクセルチューン2", cost: 1, type: "param-boost", desc: "アクセルマシンならA+10/H-2/D-2、それ以外はA+4", calc: (s, ctx) => { if(ctx.mT==="アクセル"){ s.a+=10; s.h-=2; s.d-=2; } else { s.a+=4; } } },
    { id: "0509", name: "ハンドリングチューン1", cost: 1, type: "param-boost", desc: "ハンドリングマシンならH+10/P-4、それ以外はH+4", calc: (s, ctx) => { if(ctx.mT==="ハンドリング"){ s.h+=10; s.p-=4; } else { s.h+=4; } } },
    { id: "0510", name: "ハンドリングチューン2", cost: 1, type: "param-boost", desc: "ハンドリングマシンならH+10/P-2/S-2、それ以外はH+4", calc: (s, ctx) => { if(ctx.mT==="ハンドリング"){ s.h+=10; s.p-=2; s.s-=2; } else { s.h+=4; } } },
    { id: "0511", name: "パワーチューン1", cost: 1, type: "param-boost", desc: "パワーマシンならP+10/A-4、それ以外はP+4", calc: (s, ctx) => { if(ctx.mT==="パワー"){ s.p+=10; s.a-=4; } else { s.p+=4; } } },
    { id: "0512", name: "パワーチューン2", cost: 1, type: "param-boost", desc: "パワーマシンならP+10/A-2/H-2、それ以外はP+4", calc: (s, ctx) => { if(ctx.mT==="パワー"){ s.p+=10; s.a-=2; s.h-=2; } else { s.p+=4; } } },
    { id: "0513", name: "ダッシュチューン1", cost: 1, type: "param-boost", desc: "ダッシュマシンならD+10/S-4、それ以外はD+4", calc: (s, ctx) => { if(ctx.mT==="ダッシュ"){ s.d+=10; s.s-=4; } else { s.d+=4; } } },
    { id: "0514", name: "ダッシュチューン2", cost: 1, type: "param-boost", desc: "ダッシュマシンならD+10/S-2/P-2、それ以外はD+4", calc: (s, ctx) => { if(ctx.mT==="ダッシュ"){ s.d+=10; s.s-=2; s.p-=2; } else { s.d+=4; } } },

    { id: "0601", name: "グリップ力強化", cost: 1, type: "support", desc: "滑る路面でグリップ力アップ" },
    { id: "0602", name: "落下時ブーストリカバー", cost: 1, type: "support", desc: "落下復帰時にブースト獲得" },
    { id: "0603", name: "壁リングガード", cost: 1, type: "support", desc: "壁衝突時のリング減少を防ぐ" },
    { id: "0604", name: "無敵スタート", cost: 2, type: "support", desc: "スタート直後約40秒無敵" },
    { id: "0605", name: "アイテムロスト無効化", cost: 2, type: "support", desc: "被弾時のアイテムロストを防ぐ" },
    { id: "0606", name: "クイックリカバー", cost: 3, type: "support", desc: "復帰速度アップ" },
    { id: "0607", name: "リングガード", cost: 2, type: "support", desc: "被弾時のリング減少を半減" },

    { id: "0701", name: "アイテムストックトレード", cost: 3, type: "item-control", desc: "アイテム順序入れ替え可能" },
    { id: "0702", name: "アイテムストックプラス", cost: 2, type: "item-control", desc: "アイテム所持数+1" },
    { id: "0703", name: "設置アイテム確率アップ", cost: 1, type: "item-control", desc: "設置アイテム出現率アップ" },
    { id: "0704", name: "攻撃アイテム確率アップ", cost: 1, type: "item-control", desc: "攻撃アイテム出現率アップ" },
    { id: "0705", name: "防御アイテム確率アップ", cost: 2, type: "item-control", desc: "防御アイテム出現率アップ" },
    { id: "0706", name: "加速アイテム確率アップ", cost: 3, type: "item-control", desc: "加速アイテム出現率アップ" },
    { id: "0707", name: "ウィスプ確率アップ", cost: 1, type: "item-control", desc: "ブースト・レーザー・ドリル・ボム・ヴォイドの5種が出現率アップ" },

    { id: "0801", name: "最初からブースト", cost: 1, type: "item-boost", desc: "開始時ブースト所持" },
    { id: "0802", name: "ダブルブースト追加", cost: 2, type: "item-boost", desc: "開始時ダブルブースト所持" },
    { id: "0803", name: "最初からダークチャオ", cost: 1, type: "item-boost", desc: "開始時ダークチャオ所持" },
    { id: "0804", name: "ワープリング追加", cost: 2, type: "item-boost", desc: "開始時ワープリング所持" },
    { id: "0805", name: "ロケットパンチ巨大化", cost: 1, type: "item-boost", desc: "ロケットパンチ強化" },
    { id: "0806", name: "トゲ鉄球巨大化", cost: 1, type: "item-boost", desc: "トゲ鉄球強化＆出現率アップ" },
    { id: "0807", name: "ボムクイックチャージ", cost: 1, type: "item-boost", desc: "ボム強化＆出現率アップ" },
    { id: "0808", name: "最初からモンスタートラック", cost: 3, type: "item-boost", desc: "開始時モンスタートラック所持" },

    { id: "0901", name: "ドリフトチャージ短縮キット", cost: 3, type: "standard", desc: "チャージ1-2段高速化 / H+3", calc: (s) => { s.h+=3; } },
    { id: "0902", name: "アイテムたくさんキット", cost: 3, type: "standard", desc: "アイテム3枠＆LAP2,3にアイテム獲得" },
    { id: "0903", name: "ダメージサポートキット", cost: 3, type: "standard", desc: "無敵スタート＆落下リカバー" },

    { id: "1001", name: "スピードマシンキット", cost: 3, type: "machine", desc: "リング獲得範囲アップ+リングゲットダッシュミニを内包。スピードマシンだとスピード+20、アクセル-16", calc: (s, ctx) => { if(ctx.mT==="スピード"){ s.s+=20; s.a-=16; } } },
    { id: "1002", name: "アクセルマシンキット", cost: 3, type: "machine", desc: "クイックリカバー（弱）を内包。アクセルマシンだとアクセル+20、ダッシュ-16", calc: (s, ctx) => { if(ctx.mT==="アクセル"){ s.a+=20; s.d-=16; } } },
    { id: "1003", name: "ハンドリングマシンキット", cost: 3, type: "machine", desc: "アルティメットチャージを内包。ハンドリングマシンだとハンドリング+20、スピード-16", calc: (s, ctx) => { if(ctx.mT==="ハンドリング"){ s.h+=20; s.s-=16; } } },
    { id: "1004", name: "パワーマシンキット", cost: 3, type: "machine", desc: "ぶつかりダッシュを内包。パワーマシンだとパワー+20、ハンドリング-16", calc: (s, ctx) => { if(ctx.mT==="パワー"){ s.p+=20; s.h-=16; } } },
    { id: "1005", name: "ダッシュマシンキット", cost: 3, type: "machine", desc: "チャージダッシュ時にリングを2枚獲得。ダッシュマシンだとダッシュ+20、パワー-16", calc: (s, ctx) => { if(ctx.mT==="ダッシュ"){ s.d+=20; s.p-=16; } } },

    { id: "1101", name: "ハンドリングキャラキット", cost: 3, type: "char", desc: "リングスティール、リングスティールミニを内包 ハンドリングキャラならH+7/S-5", calc: (s, ctx) => { if(ctx.cT==="ハンドリング"){ s.h+=7; s.s-=5; } } },
    { id: "1102", name: "パワーキャラキット", cost: 3, type: "char", desc: "ぶつかりダッシュ、ロングスリップストリームを内包 パワーキャラならP+7/H-5", calc: (s, ctx) => { if(ctx.cT==="パワー"){ s.p+=7; s.h-=5; } } },
    { id: "1103", name: "ダッシュキャラキット", cost: 3, type: "char", desc: "超高速エアトリック、エアトリックボーナスを内包 ダッシュキャラならD+7/P-5", calc: (s, ctx) => { if(ctx.cT==="ダッシュ"){ s.d+=7; s.p-=5; } } },

    { id: "1201", name: "後半追い上げキット", cost: 3, type: "advanced", desc: "リング上限110枚＆LAP3アイテム2つ獲得" },
    { id: "1202", name: "水上強化キット", cost: 3, type: "advanced", desc: "「超高速エアトリック」「チャージジャンプ自由度アップ」を組み合わせたキット" }
];

const usageStats = { "0402":34, "0404":33, "0403":32, "0406":31, "0901":9, "0702":9, "0707":7, "0701":6, "0102":6, "0305":4, "0401":3, "0108":2, "0513":2, "0606":1, "0514":1, "0301":1, "0105":1, "0205":1 };
const synergyData = {
    "0406": ["0402", "0404", "0403"], "0702": ["0707", "0701", "0402"],
    "0108": ["0403", "0901", "0406"], "0102": ["0305", "0901", "0406"],
    "0513": ["0406", "0514", "0404"], "0707": ["0702", "0701", "0401"],
    "0205": ["0606", "0301", "0105"], "0401": ["0402", "0403", "0404"],
    "0606": ["0301", "0205", "0105"], "0701": ["0707", "0702"],
    "0105": ["0606", "0301", "0205"], "0901": ["0305", "0102", "0403"],
    "0402": ["0404", "0406", "0403"], "0305": ["0901", "0102"],
    "0301": ["0606", "0205", "0105"], "0403": ["0404", "0402", "0406"],
    "0514": ["0406", "0513", "0404"], "0404": ["0402", "0403", "0406"]
};

const rankingData = {
    stats: {
        gadgets: [
            { name: "セカンドファストチャージ", count: 34, percent: 68.0 },
            { name: "アルティメットチャージ", count: 33, percent: 66.0 },
            { name: "サードファストチャージ", count: 32, percent: 64.0 },
            { name: "テクニカルドリフト", count: 31, percent: 62.0 },
            { name: "ドリフトチャージ短縮キット", count: 9, percent: 18.0 },
            { name: "アイテムストックプラス", count: 9, percent: 18.0 },
            { name: "ウィスプ確率アップ", count: 7, percent: 14.0 },
            { name: "アイテムストックトレード", count: 6, percent: 12.0 },
            { name: "エアトリックボーナス", count: 6, percent: 12.0 },
            { name: "超高速エアトリック", count: 4, percent: 8.0 }
        ],
        charTypes: [
            { name: "スピード", count: 18, percent: 36.0 },
            { name: "パワー", count: 14, percent: 28.0 },
            { name: "ハンドリング", count: 7, percent: 14.0 },
            { name: "アクセル", count: 7, percent: 14.0 },
            { name: "ダッシュ", count: 4, percent: 8.0 }
        ],
        machines: [
            { name: "ダッシュ", count: 39, percent: 78.0 },
            { name: "スピード", count: 7, percent: 14.0 },
            { name: "ハンドリング", count: 3, percent: 6.0 },
            { name: "パワー", count: 1, percent: 2.0 }
        ]
    },
    synergy: [
        { name: "アルティメットチャージ / サードファストチャージ / セカンドファストチャージ / テクニカルドリフト", count: 27, note: "Top50中 27人が採用" },
        { name: "アイテムストックトレード / アイテムストックプラス / ウィスプ確率アップ", count: 6, note: "Top50中 6人が採用" },
        { name: "エアトリックボーナス / ドリフトチャージ短縮キット / 超高速エアトリック", count: 4, note: "Top50中 4人が採用" },
        { name: "アルティメットチャージ / サードファストチャージ / セカンドファストチャージ / ファーストファストチャージ", count: 2, note: "Top50中 2人が採用" },
        { name: "アルティメットチャージ / エアトリックボーナス / セカンドファストチャージ / テクニカルドリフト", count: 2, note: "Top50中 2人が採用" }
    ],
    playerList: [
        { rank: 1, name: "CallieMacN", char: "エミー", charType: "ハンドリング", machineType: "ハンドリング", machineBody: "ホットハッチ", parts: ["ホットハッチ", "ホットハッチ", "ピンクカプリオレ"], gadgets: ["ドリフトチャージ短縮キット", "サードファストチャージ", "アルティメットチャージ"], stats: { speed: 22, accel: 60, handling: 81, power: 30, dash: 50 } },
        { rank: 2, name: "IndigoDestiny", char: "エミー", charType: "ハンドリング", machineType: "ハンドリング", machineBody: "マインカート", parts: ["マインカート", "マインカート", "マインカート"], gadgets: ["エアトリックボーナス", "超高速エアトリック", "ドリフトチャージ短縮キット"], stats: { speed: 26, accel: 57, handling: 71, power: 37, dash: 52 } },
        { rank: 3, name: "notnamie", char: "クリーム＆チーズ", charType: "ハンドリング", machineType: "スピード", machineBody: "ダークリーパー", parts: ["ダークリーパー", "ダークリーパー", "ダークリーパー"], gadgets: ["エアトリックボーナス", "超高速エアトリック", "ドリフトチャージ短縮キット"], stats: { speed: 67, accel: 32, handling: 58, power: 51, dash: 35 } },
        { rank: 4, name: "sneaky31415", char: "テイルス", charType: "アクセル", machineType: "スピード", machineBody: "ダークリーパー", parts: ["ダークリーパー", "ダークリーパー", "ダークリーパー"], gadgets: ["超高速エアトリック", "エアトリックボーナス", "ドリフトチャージ短縮キット"], stats: { speed: 75, accel: 38, handling: 46, power: 55, dash: 29 } },
        { rank: 5, name: "SV★TwitchKEY1DR", char: "ブレイズ(AIレーサー)", charType: "スピード", machineType: "ダッシュ", machineBody: "ウィスポンブースター", parts: ["ウィスポンブースター", "ウィスポンブースター"], gadgets: ["テクニカルドリフト", "セカンドファストチャージ", "サードファストチャージ", "アルティメットチャージ"], stats: { speed: 46, accel: 41, handling: 53, power: 33, dash: 67 } },
        { rank: 6, name: "くろぼん", char: "ソニック", charType: "スピード", machineType: "スピード", machineBody: "スピードスターライトニング", parts: ["スピードスターライトニング", "ダークリーパー", "スピードスターライトニング"], gadgets: ["アイテムストックプラス", "ウィスプ確率アップ", "アイテムストックトレード"], stats: { speed: 80, accel: 21, handling: 51, power: 59, dash: 29 } },
        { rank: 7, name: "Estabanツ", char: "セージ", charType: "アクセル", machineType: "ダッシュ", machineBody: "クワッドコプター", parts: ["クワッドコプター", "トリプルファン"], gadgets: ["アイテムたくさんキット", "ドリフトチャージ短縮キット"], stats: { speed: 39, accel: 53, handling: 57, power: 30, dash: 64 } },
        { rank: 8, name: "TimTheGamer12", char: "初音ミク", charType: "ダッシュ", machineType: "ハンドリング", machineBody: "マインカート", parts: ["マインカート", "マインカート", "マインカート"], gadgets: ["セカンドファストチャージ", "テクニカルドリフト", "サードファストチャージ", "アルティメットチャージ"], stats: { speed: 30, accel: 56, handling: 63, power: 36, dash: 55 } },
        { rank: 9, name: "SV Jonny", char: "エスピオ", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["アルティメットチャージ", "ダッシュチューン2", "テクニカルドリフト", "ダッシュチューン1"], stats: { speed: 37, accel: 37, handling: 56, power: 34, dash: 88 } },
        { rank: 10, name: "SOOOOOOOOOOOOONC", char: "ウェーブ", charType: "アクセル", machineType: "スピード", machineBody: "ロイヤルチャリオット", parts: ["ロイヤルチャリオット", "スピードスターライトニング", "レトロフューチャー"], gadgets: ["アイテムストックトレード", "アイテムストックプラス", "ウィスプ確率アップ"], stats: { speed: 74, accel: 38, handling: 42, power: 55, dash: 31 } },
        { rank: 11, name: "Triangly", char: "エミー(AIレーサー)", charType: "ハンドリング", machineType: "ダッシュ", machineBody: "タイプ-W ウィンディ", parts: ["タイプ-W ウィンディ", "タイプ-W ウィンディ"], gadgets: ["テクニカルドリフト", "セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ"], stats: { speed: 27, accel: 51, handling: 66, power: 23, dash: 73 } },
        { rank: 12, name: "MaximilianoxD2", char: "初音ミク", charType: "ダッシュ", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["アルティメットチャージ", "サードファストチャージ", "テクニカルドリフト", "セカンドファストチャージ"], stats: { speed: 35, accel: 46, handling: 57, power: 26, dash: 76 } },
        { rank: 13, name: "super", char: "ブレイズ", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["セカンドファストチャージ", "テクニカルドリフト", "アルティメットチャージ", "サードファストチャージ"], stats: { speed: 46, accel: 39, handling: 53, power: 33, dash: 69 } },
        { rank: 14, name: "Absolutely Not", char: "ブレイズ", charType: "スピード", machineType: "ダッシュ", machineBody: "ディーヴァマッキナ", parts: ["ディーヴァマッキナ", "ウィスポンブースター"], gadgets: ["テクニカルドリフト", "セカンドファストチャージ", "サードファストチャージ", "アルティメットチャージ"], stats: { speed: 47, accel: 42, handling: 54, power: 33, dash: 64 } },
        { rank: 15, name: "svRenee-", char: "ウェアホッグ", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["テクニカルドリフト", "サードファストチャージ", "セカンドファストチャージ", "アルティメットチャージ"], stats: { speed: 40, accel: 41, handling: 48, power: 36, dash: 75 } },
        { rank: 16, name: "JarLster", char: "エッグマン(AIレーサー)", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["アルティメットチャージ", "セカンドファストチャージ", "テクニカルドリフト", "サードファストチャージ"], stats: { speed: 40, accel: 40, handling: 47, power: 37, dash: 76 } },
        { rank: 17, name: "EddyK_XV", char: "ナックルズ", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-W ウィンディ", parts: ["タイプ-W ウィンディ", "タイプ-W ウィンディ"], gadgets: ["アルティメットチャージ", "サードファストチャージ", "テクニカルドリフト", "セカンドファストチャージ"], stats: { speed: 35, accel: 44, handling: 51, power: 34, dash: 76 } },
        { rank: 18, name: "NeederSpeeder345", char: "シャドウ", charType: "スピード", machineType: "ダッシュ", machineBody: "ブルースター", parts: ["ブルースター", "ブルースター"], gadgets: ["テクニカルドリフト", "セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ"], stats: { speed: 48, accel: 41, handling: 55, power: 33, dash: 63 } },
        { rank: 19, name: "ix☆Nova", char: "メタルソニック", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["ファーストファストチャージ", "セカンドファストチャージ", "アイテムストックプラス", "ウィスプ確率アップ"], stats: { speed: 45, accel: 37, handling: 55, power: 36, dash: 67 } },
        { rank: 20, name: "avie", char: "ウェアホッグ", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["アイテムストックプラス", "ダッシュチューン1", "ドリフトチャージ短縮キット"], stats: { speed: 36, accel: 41, handling: 51, power: 36, dash: 85 } },
        { rank: 21, name: "♪Panda.Z♪", char: "ルージュ", charType: "ハンドリング", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["ドリフトチャージ短縮キット", "ジャストチャージボーナス", "サードファストチャージ"], stats: { speed: 31, accel: 48, handling: 64, power: 27, dash: 73 } },
        { rank: 22, name: "PersonaSomina1up", char: "シャドウ", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["アルティメットチャージ", "セカンドファストチャージ", "テクニカルドリフト", "サードファストチャージ"], stats: { speed: 46, accel: 39, handling: 53, power: 33, dash: 69 } },
        { rank: 23, name: "NightShide303", char: "メタルソニック", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["テクニカルドリフト", "サードファストチャージ", "アルティメットチャージ", "セカンドファストチャージ"], stats: { speed: 45, accel: 37, handling: 55, power: 36, dash: 67 } },
        { rank: 24, name: "SV Busydon", char: "ドレッド", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["アルティメットチャージ", "セカンドファストチャージ", "テクニカルドリフト", "サードファストチャージ"], stats: { speed: 39, accel: 39, handling: 47, power: 40, dash: 75 } },
        { rank: 25, name: "The Hawk", char: "ザボック", charType: "パワー", machineType: "ダッシュ", machineBody: "ブルースター", parts: ["ブルースター", "ブルースター"], gadgets: ["アルティメットチャージ", "サードファストチャージ", "テクニカルドリフト", "セカンドファストチャージ"], stats: { speed: 41, accel: 41, handling: 49, power: 40, dash: 69 } },
        { rank: 26, name: "Fantaraujo", char: "テイルス", charType: "アクセル", machineType: "ダッシュ", machineBody: "タイプ-W ウィンディ", parts: ["タイプ-W ウィンディ", "タイプ-W ウィンディ"], gadgets: ["ファーストファストチャージ", "セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ"], stats: { speed: 37, accel: 56, handling: 53, power: 29, dash: 65 } },
        { rank: 27, name: "whimia", char: "ザズ", charType: "アクセル", machineType: "スピード", machineBody: "ロイヤルチャリオット", parts: ["ロイヤルチャリオット", "ロイヤルチャリオット", "ロイヤルチャリオット"], gadgets: ["アイテムストックトレード", "アイテムストックプラス", "ウィスプ確率アップ"], stats: { speed: 76, accel: 39, handling: 41, power: 52, dash: 32 } },
        { rank: 28, name: "Anhesim", char: "ルージュ", charType: "ハンドリング", machineType: "ダッシュ", machineBody: "タイプ-W ウィンディ", parts: ["タイプ-W ウィンディ", "タイプ-W ウィンディ"], gadgets: ["テクニカルドリフト", "セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ"], stats: { speed: 27, accel: 52, handling: 65, power: 23, dash: 73 } },
        { rank: 29, name: "Anon7906", char: "ナックルズ", charType: "パワー", machineType: "ダッシュ", machineBody: "ブルースター", parts: ["ブルースター", "ブルースター"], gadgets: ["アルティメットチャージ", "セカンドファストチャージ", "テクニカルドリフト", "エアトリックボーナス"], stats: { speed: 41, accel: 42, handling: 49, power: 38, dash: 70 } },
        { rank: 30, name: "SV-_-TRXSHTV", char: "スティーブ", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["テクニカルドリフト", "セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ"], stats: { speed: 38, accel: 41, handling: 48, power: 38, dash: 75 } },
        { rank: 31, name: "RobertSSJ4", char: "シャドウ", charType: "スピード", machineType: "ダッシュ", machineBody: "ブルースター", parts: ["ブルースター", "ブルースター"], gadgets: ["ファーストファストチャージ", "セカンドファストチャージ", "サードファストチャージ", "アルティメットチャージ"], stats: { speed: 48, accel: 41, handling: 55, power: 33, dash: 63 } },
        { rank: 32, name: "mikemartn67", char: "シャドウ", charType: "スピード", machineType: "スピード", machineBody: "スーパーシャイニング", parts: ["スーパーシャイニング", "スーパーシャイニング", "スーパーシャイニング"], gadgets: ["アイテムストックトレード", "アイテムストックプラス", "ウィスプ確率アップ"], stats: { speed: 74, accel: 22, handling: 50, power: 61, dash: 33 } },
        { rank: 33, name: "Gabu", char: "ビッグ", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-W ウィンディ", parts: ["タイプ-W ウィンディ", "タイプ-J イオタ"], gadgets: ["サードファストチャージ", "テクニカルドリフト", "セカンドファストチャージ", "アルティメットチャージ"], stats: { speed: 36, accel: 44, handling: 51, power: 35, dash: 74 } },
        { rank: 34, name: "Nemeon", char: "初音ミク", charType: "ダッシュ", machineType: "ダッシュ", machineBody: "タイプ-W ウィンディ", parts: ["タイプ-W ウィンディ", "タイプ-W ウィンディ"], gadgets: ["テクニカルドリフト", "サードファストチャージ", "アルティメットチャージ", "セカンドファストチャージ"], stats: { speed: 31, accel: 50, handling: 61, power: 22, dash: 76 } },
        { rank: 35, name: "Kenneth", char: "ストーム", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-S ストリーム", parts: ["タイプ-S ストリーム", "タイプ-S ストリーム"], gadgets: ["アルティメットチャージ", "サードファストチャージ", "テクニカルドリフト", "セカンドファストチャージ"], stats: { speed: 35, accel: 43, handling: 51, power: 37, dash: 74 } },
        { rank: 36, name: "✭AFX✭Fidox", char: "ナイン", charType: "アクセル", machineType: "ダッシュ", machineBody: "ウィスポンブースター", parts: ["ウィスポンブースター", "ブルースター"], gadgets: ["超高速エアトリック", "エアトリックボーナス", "ドリフトチャージ短縮キット"], stats: { speed: 42, accel: 54, handling: 53, power: 33, dash: 61 } },
        { rank: 37, name: "Missing_Ache", char: "ウェアホッグ", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["アルティメットチャージ", "セカンドファストチャージ", "テクニカルドリフト", "エアトリックボーナス"], stats: { speed: 40, accel: 41, handling: 48, power: 36, dash: 75 } },
        { rank: 38, name: "TescoReturns806", char: "エッグマン", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-W ウィンディ", parts: ["タイプ-W ウィンディ", "タイプ-W ウィンディ"], gadgets: ["ドリフトチャージ短縮キット", "セカンドファストチャージ", "アイテムストックプラス"], stats: { speed: 36, accel: 44, handling: 54, power: 33, dash: 76 } },
        { rank: 39, name: "Ghostman2135", char: "初音ミク", charType: "ダッシュ", machineType: "ダッシュ", machineBody: "タイプ-W ウィンディ", parts: ["タイプ-W ウィンディ", "タイプ-W ウィンディ"], gadgets: ["サードファストチャージ", "テクニカルドリフト", "セカンドファストチャージ", "アルティメットチャージ"], stats: { speed: 31, accel: 50, handling: 61, power: 22, dash: 76 } },
        { rank: 40, name: "WR ShyGuy", char: "ウェーブ", charType: "アクセル", machineType: "パワー", machineBody: "トレイルランナー", parts: ["トレイルランナー", "ランドスマッシャー", "トレイルランナー"], gadgets: ["クイックリカバー", "ロングスリップストリーム", "スリップストリームボーナス", "リングゲットダッシュミニ"], stats: { speed: 57, accel: 42, handling: 22, power: 67, dash: 52 } },
        { rank: 41, name: "#1 ARUUU FAN(Fa...", char: "ブレイズ", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["セカンドファストチャージ", "テクニカルドリフト", "サードファストチャージ", "アルティメットチャージ"], stats: { speed: 46, accel: 39, handling: 53, power: 33, dash: 69 } },
        { rank: 42, name: "WR Squanto", char: "ジェット(AIレーサー)", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-W ウィンディ", parts: ["タイプ-W ウィンディ", "ウィスポンブースター"], gadgets: ["アイテムストックトレード", "アイテムストックプラス", "ウィスプ確率アップ"], stats: { speed: 43, accel: 42, handling: 55, power: 32, dash: 68 } },
        { rank: 43, name: "Tyke", char: "エッグマン(AIレーサー)", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["ジャストチャージボーナス", "セカンドファストチャージ", "サードファストチャージ", "テクニカルドリフト"], stats: { speed: 40, accel: 40, handling: 47, power: 37, dash: 76 } },
        { rank: 44, name: "gt_su", char: "ジョーカー", charType: "ハンドリング", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["テクニカルドリフト", "セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ"], stats: { speed: 33, accel: 46, handling: 60, power: 30, dash: 71 } },
        { rank: 45, name: "ShiyoKitsuneTTV", char: "ブレイズ", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["テクニカルドリフト", "セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ"], stats: { speed: 46, accel: 39, handling: 53, power: 33, dash: 69 } },
        { rank: 46, name: "Heykrow", char: "ブレイズ(AIレーサー)", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["アルティメットチャージ", "サードファストチャージ", "テクニカルドリフト", "セカンドファストチャージ"], stats: { speed: 44, accel: 41, handling: 55, power: 31, dash: 69 } },
        { rank: 47, name: "evewin_mt", char: "エスピオ(AIレーサー)", charType: "スピード", machineType: "ダッシュ", machineBody: "ウィスポンブースター", parts: ["ウィスポンブースター", "ウィスポンブースター"], gadgets: ["セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ", "テクニカルドリフト"], stats: { speed: 35, accel: 40, handling: 54, power: 31, dash: 68 } },
        { rank: 48, name: "YUDI", char: "ナックルズ", charType: "パワー", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ", "テクニカルドリフト"], stats: { speed: 38, accel: 41, handling: 48, power: 38, dash: 75 } },
        { rank: 49, name: "Dann", char: "ジェット", charType: "スピード", machineType: "ダッシュ", machineBody: "タイプ-J イオタ", parts: ["タイプ-J イオタ", "タイプ-J イオタ"], gadgets: ["テクニカルドリフト", "セカンドファストチャージ", "アルティメットチャージ", "サードファストチャージ"], stats: { speed: 45, accel: 39, handling: 53, power: 34, dash: 68 } },
        { rank: 50, name: "zDyxasty", char: "ソニック", charType: "スピード", machineType: "スピード", machineBody: "スピードスターライトニング", parts: ["スピードスターライトニング", "スピードスターライトニング", "スピードスターライトニング"], gadgets: ["アイテムストックトレード", "アイテムストックプラス", "ウィスプ確率アップ"], stats: { speed: 80, accel: 20, handling: 52, power: 60, dash: 28 } }
    ]
};
